name: Test Deploy VS Code Extension

on:
  push:
    branches:
      - main
      - test-branch  # Add a test branch for testing purposes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Check if version bumped
        uses: johnnybenson/package-json-versioned-action@v1.0.5
        id: package-json
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Output version bump results
        run: |
          echo "has-updated -- ${{ steps.package-json.outputs.has-updated }}"
          echo "previous-version -- ${{ steps.package-json.outputs.previous-version }}"
          echo "version -- ${{ steps.package-json.outputs.version }}"
          echo "Outputs: ${{ toJson(steps.package-json.outputs) }}"
          echo '${{ toJson(steps.package-json.outputs) }}' | jq -r 'to_entries|map("\(.key) -- \(.value)")|.[]'

      - name: Simulate Publish VS Code Extension
        if: steps.package-json.outputs.has-updated
        env:
          VSCE_PAT: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        run: |
          echo "Version bumped detected. Would publish now."
          # Uncomment the line below to actually install vsce for a full test without publishing
          # npm install -g vsce
          # Uncomment the line below to simulate vsce publish
          # echo "vsce publish --no-publish"
